
;--------------------------------------------------
;FlameCar
;--------------------------------------------------
; UP
upFName_F db 'bin/flameU.bin',0
; DOWN
downFName_F db 'bin/flameD.bin',0
; LEFT
leftFName_F db 'bin/flameL.bin',0
; RIGHT
rightFName_F db 'bin/flameR.bin',0
; UP LEFT 
upleftFName_F db 'bin/flameUL.bin',0
; UP RIGHT
uprightFName_F db 'bin/flameUR.bin',0
; DOWN LEFT
downleftFName_F db 'bin/flameDL.bin',0
; DOWN RIGHT
downrightFName_F db 'bin/flameDR.bin',0
;--------------------------------------------------
;RED CAR
;----------------------------------------------------------
; UP
upFName_R db '/bin/redU.bin',0
; DOWN
downFName_R db '/bin/redD.bin',0
; LEFT
leftFName_R db '/bin/redL.bin',0
; RIGHT
rightFName_R db '/bin/redR.bin',0
; UP LEFT 
upleftFName_R db '/bin/redUL.bin',0
; UP RIGHT
uprightFName_R db '/bin/redUR.bin',0
; DOWN LEFT
downleftFName_R db '/bin/redDL.bin',0
; DOWN RIGHT
downrightFName_R db '/bin/redDR.bin',0
;---------------------------------------------------------
;YELLOW CAR
;----------------------------------------------------
; UP
upFName_Y db '/bin/yU.bin',0
; DOWN
downFName_Y db '/bin/yD.bin',0
; LEFT
leftFName_Y db '/bin/yL.bin',0
; RIGHT
rightFName_Y db '/bin/yR.bin',0
; UP LEFT 
upleftFName_Y db '/bin/yUL.bin',0
; UP RIGHT
uprightFName_Y db '/bin/yUR.bin',0
; DOWN LEFT
downleftFName_Y db '/bin/yDL.bin',0
; DOWN RIGHT
downrightFName_Y db '/bin/yDR.bin',0
;------------------------------------------------------
;BLUE CAR :
;-------------------------------------------
; UP
upFName_B db '/bin/bU.bin',0
; DOWN
downFName_B db '/bin/bD.bin',0
; LEFT
leftFName_B db '/bin/bL.bin',0
; RIGHT
rightFName_B db '/bin/bR.bin',0
; UP LEFT 
upleftFName_B db '/bin/bUL.bin',0
; UP RIGHT
uprightFName_B db '/bin/bUR.bin',0
; DOWN LEFT
downleftFName_B db '/bin/bDL.bin',0
; DOWN RIGHT
downrightFName_B db '/bin/bDR.bin',0
;-------------------------------------------



