; UP
upFName_F db '/flabin/flameU.bin',0


; DOWN
downFName_F db '/flabin/flameD.bin',0


; LEFT
leftFName_F db '/flabin/flameL.bin',0


; RIGHT
rightFName_F db '/flabin/flameR.bin',0


; UP LEFT 
upleftFName_F db '/flabin/flameUL.bin',0


; UP RIGHT
uprightFName_F db '/flabin/flameUR.bin',0


; DOWN LEFT
downleftFName_F db '/flabin/flameDL.bin',0


; DOWN RIGHT
downrightFName_F db '/flabin/flameDR.bin',0
