; UP
upFName_R db '/redbin/redU.bin',0
upF_R db verti_size dup(?)

; DOWN
downFName_R db '/redbin/redD.bin',0
downF_R db verti_size dup(?)

; LEFT
leftFName_R db '/redbin/redL.bin',0
leftF_R db horiz_size dup(?)

; RIGHT
rightFName_R db '/redbin/redR.bin',0
rightF_R db horiz_size dup(?)

; UP LEFT 
upleftFName_R db '/redbin/redUL.bin',0
upleftF_R db diag_size dup(?)

; UP RIGHT
uprightFName_R db '/redbin/redUR.bin',0
uprightF_R db diag_size dup(?)

; DOWN LEFT
downleftFName_R db '/redbin/redDL.bin',0
downleftF_R db diag_size dup(?)

; DOWN RIGHT
downrightFName_R db '/redbin/redDR.bin',0
downrightF_R db diag_size dup(?)



