; UP
upFName_Y db '/yellowBin/yelloU.bin',0

; DOWN
downFName_Y db '/yellowBin/yelloD.bin',0

; LEFT
leftFName_Y db '/yellowBin/yelloL.bin',0

; RIGHT
rightFName_Y db '/yellowBin/yelloR.bin',0

; UP LEFT 
upleftFName_Y db '/yellowBin/yelloUL.bin',0

; UP RIGHT
uprightFName_Y db '/yellowBin/yelloUR.bin',0

; DOWN LEFT
downleftFName_Y db '/yellowBin/yelloDL.bin',0

; DOWN RIGHT
downrightFName_Y db '/yellowBin/yelloDR.bin',0


